import turtle
import math

t = turtle.Turtle()
t.screen.setup(width=1920, height=1080)
t.speed(0)
t.penup()
t.goto(0,-300)
t.setheading(90.0)
t.pendown()

F_LEN = 20.0
G_LEN = 30.0
PEN_STACK = []

t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('blue')
t.forward(F_LEN)
PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.right(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

PEN_STACK.append((t.heading(), t.pos()))
t.penup()
t.left(25)
t.pencolor('red')
t.forward(G_LEN)
if PEN_STACK:
  heading, pos = PEN_STACK.pop()
  t.setheading(heading)
  t.goto(pos)
  t.pendown()

t.pencolor('blue')
t.forward(F_LEN)
t.pencolor('red')
t.forward(G_LEN)

t.screen.exitonclick()